version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Enforce semantic release convention.
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
        # All todo check boxes must be checked.
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
      - do: approvals
        min:
          count: 1
        or:
          - required:
              reviewers: [ jusx ]
          - required:
              reviewers: [ shine2lay ]
      - do: or
        # if the PR is a new feature or a fix, it must be logged in the changelog
        validate:
          - do: and
            validate:
              - do: title
                must_include:
                  regex: ^(feat|fix)(\(\w+\))?:.+$
              - do: changeset
                must_include:
                  regex: 'docs/changelog.rst'
                  message: 'new features or fixes needed to be logged to the changelog'
          - do: title
            must_exclude:
              regex: ^(feat|fix)(\(\w+\))?:.+$
              message: 'new features or fixes needed to be logged to the changelog'
    pass:
      - do: merge
        merge_method: 'squash'
      - do: checks
        status: 'success'
