# .github/workflows/ci.yml

name: Ruby CI

on:
  push:
    branches: [master] 
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          # This automatically runs 'bundle install' and caches gems
          # It uses the Gemfile.lock for efficient caching
          bundler-cache: true

      - name: Run RSpec tests
        run: bundle exec rspec